### ISSUE TITLE
error on compelling

### ISSUE THREAD

**Issue by demenkovms** [prepkg/tensorflow-lite-raspberrypi#1]
Hello. I'm get an error:

```
root@orangepi3-lts:/home/orangepi# g++ main.cpp -o test -ltensorflow-lite -ldl
/usr/bin/ld: skipping incompatible //usr/local/lib/libtensorflow-lite.so when searching for -ltensorflow-lite
/usr/bin/ld: cannot find -ltensorflow-lite
collect2: error: ld returned 1 exit status
```

use Orange Pi3 + Debian 

The installed was ok

**Comment by prepkg** [comment]
Precompiled TensorFlow Lite binaries are only compatible with Raspberry Pi OS Bullseye (32-bit). Supported boards: Raspberry Pi 3 Model A+/B+ and Raspberry Pi 4 Model B.
