### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by aaronhsueh0506** [prepkg/tensorflow-lite-raspberrypi#2]
Hi, 

I try to use C++ API use this code 
``g++ test.cpp -o test -ltensorflow-lite -ldl -lm``
and get these error message as below
```
/usr/bin/ld: //usr/local/lib/libtensorflow-lite.so: undefined reference to `log@GLIBC_2.29'
/usr/bin/ld: //usr/local/lib/libtensorflow-lite.so: undefined reference to `exp@GLIBC_2.29'
/usr/bin/ld: //usr/local/lib/libtensorflow-lite.so: undefined reference to `pow@GLIBC_2.29'
collect2: error: ld returned 1 exit status
```

do you have any suggestion?
thanks

**Comment by prepkg** [comment]
Precompiled binaries are compatible with Raspberry Pi OS Bullseye. Perhaps, you are using older version of Raspberry Pi OS. Update to the latest version.
