### ISSUE TITLE
How to build one's own model.tflite?

### ISSUE THREAD

**Issue by baqwas** [prepkg/tensorflow-lite-raspberrypi#3]
Appreciate the linear regression example - very helpful in confirming the installation of the shared libraries.

How does one build one's own **model.tflite** file (other than work through the Colab exercises)? Links to other examples welcome, please, because I don't want to get lost in the weeds trying code that will not work on Raspberry Pi platforms. Thanks.

Regards.

**Comment by prepkg** [comment]
Hi,
You can read a [post](https://lindevs.com/convert-tensorflow-2-model-to-tensorflow-lite-model). It explains how to train a simple TensorFlow 2 model and then convert it to TensorFlow Lite model. This post can be a good starting point.
